In [1]:
import numpy as np

In [2]:
#numpy arrays - vectors and matrices

In [3]:
my_list = [-1,0,1] #create list and check a type
my_list, type(my_list)

([-1, 0, 1], list)

In [4]:
my_array = np.array(my_list) #create numpy array using python data structure list
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [6]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]] #create a matrix
my_matrix, type(my_matrix)

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], list)

In [8]:
matrix_one = np.array(my_matrix) #create 2-dim matrix using numpy array
matrix_one, type(matrix_one)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), numpy.ndarray)

In [10]:
my_tuple = (-1,0,1) #create tuple using numpy array
my_array_t = np.array(my_tuple)
my_array_t, type(my_array_t)

(array([-1,  0,  1]), numpy.ndarray)

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.arange(0,11,2, dtype = float) #create numpy with float type

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [13]:
np.linspace(1,15,15) #create 15 equally spaced points using linspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [14]:
np.linspace(1,15,15, retstep = True) #add step size

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.]), 1.0)

In [18]:
np.linspace(1,15,30, retstep = True) #add step size

(array([ 1.        ,  1.48275862,  1.96551724,  2.44827586,  2.93103448,
         3.4137931 ,  3.89655172,  4.37931034,  4.86206897,  5.34482759,
         5.82758621,  6.31034483,  6.79310345,  7.27586207,  7.75862069,
         8.24137931,  8.72413793,  9.20689655,  9.68965517, 10.17241379,
        10.65517241, 11.13793103, 11.62068966, 12.10344828, 12.5862069 ,
        13.06896552, 13.55172414, 14.03448276, 14.51724138, 15.        ]),
 0.4827586206896552)

In [22]:
np.zeros((4,6)) #create 2-dim matrix with 6 columns and 4 rows where value is 0

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.ones((4,6)) #create 2-dim matrix with 6 columns and 4 rows where value is 1

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.random

<module 'numpy.random' from '/Users/Vsevolod/anaconda3/lib/python3.7/site-packages/numpy/random/__init__.py'>

In [31]:
np.random.rand(3)

array([0.00780898, 0.68907227, 0.88071621])

In [32]:
np.random.rand(3,2)

array([[0.28389865, 0.18949695],
       [0.8406795 , 0.87818072],
       [0.46612024, 0.13614131]])

In [35]:
np.random.randn(3) #provide standard Gaussian distribution for 3

array([ 0.69270569, -0.56413535, -0.31501279])

In [36]:
np.random.randn(4,4) #provide standard Gaussian distribution of the function in 4 columns and 4 rows

array([[ 0.2543784 ,  1.13956368,  0.38003252, -0.95248055],
       [-1.42241199, -0.35141407,  0.50453792, -1.12713621],
       [ 1.27190441, -1.98884281,  0.57834895,  1.44900435],
       [-0.206834  ,  1.46709375, -1.60084576, -0.20139359]])

In [37]:
np.random.randint(1,100) #Return random integers from `low` (inclusive) to `high` (exclusive).- single number


79

In [38]:
np.random.randint(1,100, (4,4)) #Return random integers for 4 dim matrix

array([[26, 54, 80, 50],
       [67,  9, 35, 85],
       [70, 97, 70, 12],
       [62, 77, 58, 18]])

In [42]:
array_arange = np.arange(16)

In [43]:
array_ranint = np.random.randint(1,100, 10)

In [44]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
array_ranint

array([30,  3, 99, 36, 98, 83, 83, 99, 52, 15])

In [46]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
array_ranint.max()

99

In [48]:
array_ranint.min()

3

In [ ]:
argmax() and argmin()

In [49]:
array_ranint.argmax()

2

In [50]:
array_ranint.argmin()

1

In [52]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
array_arange.shape

(16,)

In [54]:
array_arange.size

16

In [55]:
array_arange.dtype

dtype('int64')

In [57]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
array_arange.reshape(1,16).shape

(1, 16)

In [62]:
array_1d = np.array(([-10,-2,0,2,17,106,200]))
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [64]:
array_1d[0]

-10

In [65]:
array_1d[0:3], array_1d

(array([-10,  -2,   0]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [66]:
array_1d[-2], array_1d

(106, array([-10,  -2,   0,   2,  17, 106, 200]))

In [67]:
array_1d[:2], array_1d

(array([-10,  -2]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [68]:
array_1d[2:], array_1d

(array([  0,   2,  17, 106, 200]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [69]:
array_1d[100], array_1d 

IndexError: index 100 is out of bounds for axis 0 with size 7

In [70]:
array_2d = np.arange(24)
array_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [72]:
array_2d = np.arange(24).reshape(6,4)
array_2d 


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [75]:
array_2d[row][col]
array_2d[row,col]

In [77]:
array_2d[2,2]

10

In [78]:
array_2d[1]

array([4, 5, 6, 7])

In [79]:
row = 2
col = 3
array_2d[row,col]

11

In [81]:
array_2d[2:4,2:4]

array([[10, 11],
       [14, 15]])

## Broadcasting

In [82]:
#Broadcasting
array_1d = np.arange(0,10)
array_1d 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
array_1d[0:5] = 500 #broadcast 500 in 1d array
array_1d 

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [86]:
array_2d = np.ones((4,4))
array_2d 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [87]:
array_2d[0] = 300 #broadcast 300 in 2d array
array_2d 

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [88]:
arr = np.arange(0,4)
arr

array([0, 1, 2, 3])

In [89]:
array_2d + arr

array([[300., 301., 302., 303.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.]])

In [90]:
array_2d + 300

array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [91]:
arr


array([0, 1, 2, 3])

In [93]:
arr2 = np.arange(0,4)[:, np.newaxis]
arr2

array([[0],
       [1],
       [2],
       [3]])

In [94]:
arr2+arr

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

## Fancy Indexing

In [95]:
array_2d = np.ones((5,5)) #create zero matrix
array_2d.shape[1]         #use shape attribute 
for i in range(array_2d.shape[1]): #create a loop for shape attribute
    array_2d[i] = i
array_2d                          #print matrix

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [96]:
array_2d[[3,0,1]]

array([[3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [98]:
array_2d = np.arange(24) 
array_2d.shape = (6,4)
array_2d          

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [99]:
array_2d[[2,4]]

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [100]:
array_2d[[5,0]]

array([[20, 21, 22, 23],
       [ 0,  1,  2,  3]])

In [101]:
array_2d[:,[2,3]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

## Boolean masking

In [102]:
arr_1 = np.arange(1,11)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
bool_mask = arr_1 > 3
bool_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [105]:
mod_2_mask_id = 0 ==arr_1 %2
mod_2_mask_id

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [106]:
mod_2_mask_id2 = 0 ==arr_1 %3
mod_2_mask_id2

array([False, False,  True, False, False,  True, False, False,  True,
       False])

In [107]:
ev_val = arr_1[mod_2_mask_id]
ev_val

array([ 2,  4,  6,  8, 10])

In [108]:
ev_val2 = arr_1[mod_2_mask_id2]
ev_val2

array([3, 6, 9])

In [109]:
array_2d = np.arange(24) 
array_2d.shape = (6,4)
mask_mod_2_2d = 0 ==array_2d % 2    

In [111]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [110]:
mask_mod_2_2d

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [112]:
array_2d[mask_mod_2_2d]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

## Arithmetic Operations & Universal Functions

In [113]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [114]:
arr + arr

array([0, 2, 4, 6, 8])

In [115]:
arr * arr

array([ 0,  1,  4,  9, 16])

In [116]:
arr - arr

array([0, 0, 0, 0, 0])

In [117]:
arr / arr

/Users/Vsevolod/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.])

In [118]:
1/arr

/Users/Vsevolod/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [119]:
arr ** 2

array([ 0,  1,  4,  9, 16])

In [120]:
2 * arr

array([0, 2, 4, 6, 8])

In [121]:
arr

array([0, 1, 2, 3, 4])

In [122]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [123]:
np.max(arr)

4

In [124]:
np.min(arr)

0

In [125]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [126]:
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [127]:
np.log(arr)

/Users/Vsevolod/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [128]:
np.deg2rad(arr)

array([0.        , 0.01745329, 0.03490659, 0.05235988, 0.06981317])

In [129]:
np.deg2rad(arr)

array([0.        , 0.01745329, 0.03490659, 0.05235988, 0.06981317])

In [131]:
np.rad2deg(np.deg2rad(arr))

array([0., 1., 2., 3., 4.])

# Practice Exersizes

In [ ]:
# What is the major difference between vector and matrix. Vector - single row/column. Matrix - multiple row/column.

In [132]:
# How to import numpy library. 
import numpy as np

In [133]:
# Convert the python list into NumPy array and check the data type.
list_1 = [1,2,3,4,5]
list_1

[1, 2, 3, 4, 5]

In [134]:
my_array = np.array(list_1)
my_array, type(my_array)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [136]:
# Generate array [0,1,2,3,4,5] using Numpy built in Function, arange()
list(np.arange(0,6))

[0, 1, 2, 3, 4, 5]

In [142]:
# Generate array of 5 zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [143]:
#Generate matrix 3 rows, 4 columns and all zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [144]:
# Generate array of 5 "1"
np.ones(5)

array([1., 1., 1., 1., 1.])

In [146]:
# Generate array of 5 "10"
np.ones(5)+9

array([10., 10., 10., 10., 10.])

In [150]:
#Use arange to generate an array of even numbers between 50 and 100(50 and 100 not included)
np.arange(52,100,2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

In [161]:
#Generate an array of 10 lineary space points between 0 and 1
np.linspace(0,1,10, retstep = True)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

In [170]:
#Generate a vector array of 25 numbers
#write a code to covert it into 2d matrix using re-shape
#can we still use shape instead of reshape
new_array = np.arange(25)
new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [175]:
new_array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [180]:
new_array.shape = (5,5)
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [181]:
#Generate Matrix 5,5 from 0 to 2.5
np.arange(1,26).reshape(5,5)/10

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

In [188]:
#Write a code to generate the matrix 0,25 step size 1 and print
print(np.linspace(0,24,25).reshape((5,5)))
print('Step size is', np.linspace(0,24,25)[1])

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
Step size is 1.0


In [189]:
#what is the main difference between  linspace and arange. Arange take a 3rd argument as a step size while linspace 
#takes number of points we want in output

In [191]:
#how to generate a single random number using NumPy built in function
np.random.rand(1)

array([0.45961024])

In [196]:
#Write a code to generate a 7 by 5 matrix of 35 random numbers
np.random.rand(35).reshape(7,5)

array([[0.9778123 , 0.91512424, 0.94547412, 0.81871482, 0.27834012],
       [0.63559114, 0.66395942, 0.65075212, 0.56581788, 0.38897253],
       [0.68295765, 0.33178047, 0.25000657, 0.93564534, 0.24537669],
       [0.0410978 , 0.24622041, 0.0879969 , 0.64566515, 0.76725339],
       [0.37934053, 0.35277596, 0.16166617, 0.02649135, 0.13678533],
       [0.96101422, 0.19048777, 0.03263569, 0.70807813, 0.04818183],
       [0.99110481, 0.62018475, 0.71270518, 0.99278942, 0.08835476]])

In [199]:
# Generate identity matrix 5 by 5
np.eye(5)*5 

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [202]:
# Generate the following matrix 6 by 5 called array_2d and provide different outputs
array_2d = np.arange(30).reshape(6,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [209]:
array_2d[3:,[2,3,4]]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [220]:
print(array_2d[5,4])

29


In [223]:
array_2d[:3,1:2]

array([[ 1],
       [ 6],
       [11]])

In [234]:
array_2d[2,:]

array([10, 11, 12, 13, 14])

In [246]:
array_2d[2:4,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [247]:
#calculate the sum of all the numbers in array_2d
array_2d.sum()

435

In [251]:
#calculate the sum of all the rows and columns in array_2d
print('Row sum: ', array_2d.sum(axis = 1)) # sum of all the rows
print('Col sum: ', array_2d.sum(axis = 1)) # sum of all the rows

Row sum:  [ 10  35  60  85 110 135]
Col sum:  [ 10  35  60  85 110 135]


In [252]:
# Calculate a standard deviation for array 2d
array_2d.std()

8.65544144839919

In [254]:
#Create boolean mask and list out the numbers that are divisible by 3 in array_2d
array_2d = np.arange(1,30)
array_2d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [255]:
bool_mask = 0 != array_2d % 3
bool_mask

array([ True,  True, False,  True,  True, False,  True,  True, False,
        True,  True, False,  True,  True, False,  True,  True, False,
        True,  True, False,  True,  True, False,  True,  True, False,
        True,  True])

In [256]:
array_2d[bool_mask]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])